INSERT INTO Jokes(prompt), VALUES
    ('Excuse me but do you like Wendys?'),
    ('Excuse me but do you Bofa?'),
    ('Hey, are you familar with Landon?'),
    ('Do you remember that guy Willya?'),
    ('Hi there, I heard that you are a huge fan of Dee.'),
    ('Excuse me but do you like pudding?'),
    ('Do you enjoy parodies?'),
    ('Have you seen the film Bofa?'),
    ('Have you met my friend Phillip?'),
    ('Hey there buddy, I have a bunch of old albums, would you like 2 cd''s?'),
    ('Do you like Imagine Dragons?'),
    ('Do you know who is coming to our party later on?'),
    ('Have you considered leaving?'),
    ('Knock knock.'),
    ('I think you should be a goblin this halloween.'),
    ('Do you prefer the Yankees or the Expos?'),
    ('Hey do you like Chef Boyardee?'),
    ('Do you know the new rapper Willya?'),
    ('How do you say ''Yes, I would like some'' in Spanish?'),
    ('You: Dee was asking after you the other day.'),
    ('Do you like Vanessa Paradis?'),
    ('Have you heard about this new breed of bunnies that have been emerging all over town?',),
    ('Have you heard about the news in Kenya today?'),
    ('In all your subjects I am giving you D''s.'),
    ('Have you played that Xbox game ''Sea Of Thieves''?'),
    ('I was shopping at the local farmers market and purchased some fermented succondese.'),
    ('I am so sick of this, it sucks!'),
    ('Hey Mike, is Phil there?'),
    ('Have you seen Dr. Botha?'),
    ('Excuse me but do you know Candice?'),
    ('How do you pronounce amoood spelled backwards?'),
    ('My girlfriend Jenny got diagnosed with DN'),
    ('I can''t believe that Sophia speaks Ligondese.'),
    ('Do you like tulips?'),
    ('Are you planning to go to SAWCON this year?'),
    ('You need to shut up before you end up like Ken'),
    ('Have you heard of E10, that new space ship?'),
    ('Did you hear about what happened in Norway?'),
    ('Have you heard of the Sugondese transfer student?'),
    ('You ever played wipe sumo?'),
    ('I need you to work on Field E today.'),
    ('Have you tried that new burget with the jalapeños?'),
    ('What''s the name of the current Rusian president?'),
    ('Did you see the news with the South China Sea?'),
    ('What''s the male actor in the Penthouse K-Drama?'),
    ('How much did your trip to Dubai cost?')
